SmartGlassWidget:

<SmartGlassWidget>:
    BoxLayout:
        orientation: "vertical"
        size: root.size
        BoxLayout:
            Image:
                source: root.image_L_src
            Image:
                source: root.image_R_src
                
        Button:
            size_hint_y:0.2
            text:"Start App"
            color: 1,0.5,0,1
            on_press: root.StartbuttonClicked()
